# Generated by Django 5.1 on 2025-08-21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('app', '0002_profile_bio'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddField(
			model_name='profile',
			name='followers',
			field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
		),
	]


