# Generated by Django 5.1 on 2025-08-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_photos/default.jpg', upload_to='profile_photos/'),
        ),
    ]
