# Generated by Django 5.1 on 2025-08-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tag_thread_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
